import type { Metadata } from "next";
import { Mulish } from "next/font/google";
import { ClerkProvider } from '@clerk/nextjs'
import { dark } from "@clerk/themes";
import "./globals.css";

const mulish = Mulish({
  variable: "--font-mulish",
  subsets: ["latin-ext"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider appearance={{
      baseTheme: dark,
    }}>
      <html lang="en">
        <body className={`${mulish.variable} antialiased dark`}>
            <div className="flex flex-col h-full overflow-hidden">
              {children}
            </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
